owner: lucat1
repo: status.teapot.ovh

sites:
  - name: "Host: honey"
    check: "tcp-ping"
    url: honey.teapot.ovh
    port: 2222
    assignees:
    - lucat1

  - name: "Host: kepler"
    check: "tcp-ping"
    url: kepler.teapot.ovh
    port: 2222
    assignees:
    - samuelemusiani

  - name: "LDAP: honey STARTTLS"
    check: "tcp-ping"
    url: ldap1.teapot.ovh
    port: 389
    assignees:
    - lucat1

  - name: "LDAP: honey TLS"
    check: "tcp-ping"
    url: ldap1.teapot.ovh
    port: 636
    assignees:
    - lucat1

  - name: "LDAP: kepler STARTTLS"
    check: "tcp-ping"
    url: ldap2.teapot.ovh
    port: 389
    assignees:
    - samuelemusiani

  - name: "LDAP: kepler TLS"
    check: "tcp-ping"
    url: ldap2.teapot.ovh
    port: 636
    assignees:
    - samuelemusiani

  - name: "Mail: honey SMTP"
    check: "tcp-ping"
    url: mail.teapot.ovh
    port: 25
    assignees:
    - lucat1

  - name: "Mail: honey Submission"
    check: "tcp-ping"
    url: mail.teapot.ovh
    port: 587
    assignees:
    - lucat1

assignees:
  - lucat1
  - samuelemusiani

status-website:
  cname: status.teapot.ovh
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Teapot Status
  introTitle: "Teapot services status board"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
